language: android
jdk: oraclejdk8
sudo: false
env:
  global:
    - GRADLE_OPTS="-Xmx512m"
  matrix:
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - build-tools-25.0.0
    - platform-tools
    - android-25
    - sys-img-armeabi-v7a-android-21
    - addon-google_apis-google-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-license-.*'
    - '.*intel.+'

before_install:
  - cp ci/AndroidManifest.xml OpenTreeMapSkinned/AndroidManifest.xml
  - export "JAVA8_HOME=/usr/lib/jvm/java-8-oracle"
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI --skin WVGA800
  - sleep 5
  - emulator -avd test -no-skin -no-audio -no-window &
  - sleep 30

before_script:
  - ./ci/wait_for_emulator.sh
  - adb shell input keyevent 82 &

script: ./gradlew OpenTreeMap:connectedCheck -PdisablePreDex
